"""Live Bracket Orders — IBKR Execution via Docker IB Gateway.

Reads signals from signals.csv (generated by market_radar_telegram.py),
places Marketable Limit + Trailing Stop brackets via IBKR API,
and inserts trades into Supabase.

Order flow:
  1. Load signals.csv -> list of targets
  2. Fetch current market price via IBKR snapshot
  3. Parent: LMT BUY at current_price * 1.003 (0.3% above -> ensures fill)
  4. Child:  TRAIL STOP SELL with auxPrice = trailing amount
  5. transmit=False on parent, transmit=True on child -> atomic submission
  6. INSERT trade into Supabase trades table
"""

import asyncio
import os
from datetime import datetime
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

# Python 3.12+ removed implicit event loop creation — ib_insync needs one at import time
asyncio.set_event_loop(asyncio.new_event_loop())

from ib_insync import IB, Stock, Order

# ── Load environment ─────────────────────────────────────────────────────
load_dotenv(Path(__file__).parent / ".env")

# ── Connection (Docker IB Gateway paper trading port) ────────────────────
HOST = "127.0.0.1"
PORT = 4002
CLIENT_ID = 3

# ── Limit Price Buffer ───────────────────────────────────────────────────
LMT_BUFFER_PCT = 0.003  # 0.3% above current price

# ── Signals file (written by market_radar_telegram.py) ───────────────────
SIGNALS_CSV = Path(__file__).parent / "signals.csv"

# ── Supabase REST ────────────────────────────────────────────────────────
SUPABASE_URL = os.environ.get("SUPABASE_URL", "").strip()
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "").strip()


class SupabaseREST:
    """Lightweight Supabase REST wrapper using httpx."""

    def __init__(self, url: str, key: str):
        import httpx
        self.base = f"{url}/rest/v1"
        self.headers = {
            "apikey": key,
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
            "Prefer": "return=representation",
        }
        self.client = httpx.Client(headers=self.headers, timeout=15)

    def insert(self, table: str, data: dict) -> list:
        resp = self.client.post(f"{self.base}/{table}", json=data)
        resp.raise_for_status()
        return resp.json()


def load_signals() -> list[dict]:
    """Load targets from signals.csv. Returns empty list if no signals."""
    if not SIGNALS_CSV.exists():
        return []
    try:
        df = pd.read_csv(SIGNALS_CSV)
    except Exception:
        return []
    if df.empty:
        return []
    targets = []
    for _, row in df.iterrows():
        targets.append({
            "ticker": str(row["ticker"]),
            "qty": int(row["shares"]),
            "trailing_amt": float(row["trailing_amt"]),
            "stop": float(row["stop"]),
            "tp": float(row["tp"]),
            "confidence": int(row.get("confidence", 0)),
        })
    return targets


def banner(text: str) -> None:
    w = 78
    print(f"\n{'=' * w}")
    print(f"  {text}")
    print(f"{'=' * w}")


def section(text: str) -> None:
    print(f"\n  --- {text} ---")


def fetch_current_price(ib: IB, contract: Stock) -> float:
    """Fetch the current market price via IBKR snapshot data.

    Tries live snapshot first. If the account lacks live market data
    subscription (Error 10089), falls back to delayed data (reqMarketDataType 3).
    Ultimate fallback: Yahoo Finance last close.
    """
    # Try live snapshot first
    ticker = ib.reqMktData(contract, "", True, False)  # snapshot=True
    ib.sleep(2)

    price = ticker.last
    if price is None or price != price:  # NaN check
        price = ticker.close
    if price is None or price != price:
        price = ticker.marketPrice()

    ib.cancelMktData(contract)

    # If live failed, try delayed data
    if not price or price != price or price <= 0:
        ib.reqMarketDataType(3)  # switch to delayed
        ticker = ib.reqMktData(contract, "", True, False)
        ib.sleep(2)

        price = ticker.last
        if price is None or price != price:
            price = ticker.close
        if price is None or price != price:
            price = ticker.marketPrice()

        ib.cancelMktData(contract)
        ib.reqMarketDataType(1)  # switch back to live

    # Ultimate fallback: Yahoo Finance
    if not price or price != price or price <= 0:
        try:
            import yfinance as yf
            df = yf.download(contract.symbol, period="5d", auto_adjust=True, progress=False)
            if hasattr(df.columns, 'get_level_values'):
                df.columns = df.columns.get_level_values(0)
            price = float(df["Close"].iloc[-1])
            print(f"    (price via Yahoo Finance fallback)")
        except Exception:
            price = 0.0

    return float(price) if price and price == price else 0.0


def create_bracket_order(
    action: str,
    quantity: int,
    limit_price: float,
    trailing_amount: float,
) -> list[Order]:
    """Create a 2-leg bracket: Marketable Limit Entry + Trailing Stop.

    Leg 1 (Parent):  Limit BUY at limit_price (0.3% above market -> fills immediately).
    Leg 2 (Child):   Trailing Stop SELL with auxPrice = trailing distance in dollars.

    transmit=False on parent -> order is held until child transmits.
    transmit=True on child   -> fires the entire group atomically.
    """
    # ── Parent: Marketable Limit Entry ────────────────────────────────
    parent = Order()
    parent.action = action
    parent.orderType = "LMT"
    parent.totalQuantity = quantity
    parent.lmtPrice = round(limit_price, 2)
    parent.tif = "GTC"
    parent.transmit = False  # HELD — do not send yet

    # ── Child: Trailing Stop ──────────────────────────────────────────
    trail_stop = Order()
    trail_stop.action = "SELL"
    trail_stop.orderType = "TRAIL"
    trail_stop.totalQuantity = quantity
    trail_stop.auxPrice = round(trailing_amount, 2)  # trailing distance in $
    trail_stop.tif = "GTC"
    trail_stop.parentId = parent.orderId
    trail_stop.transmit = True  # fires the entire bracket

    return [parent, trail_stop]


def db_insert_trade(db: SupabaseREST, trade: dict) -> None:
    """Insert a trade record into Supabase. Logs errors but doesn't crash."""
    try:
        db.insert("trades", trade)
        print(f"    -> Supabase INSERT OK ({trade['ticker']})")
    except Exception as e:
        print(f"    -> Supabase INSERT FAILED ({trade['ticker']}): {e}")


def main() -> None:
    # ── Load signals from CSV ─────────────────────────────────────────
    targets = load_signals()
    if not targets:
        print("  No signals in signals.csv. Nothing to execute.")
        return

    banner(f"IBKR LIVE BRACKET ORDERS  |  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"  Mode:       PAPER TRADING")
    print(f"  Strategy:   Marketable Limit + Trailing Stop")
    print(f"  Endpoint:   {HOST}:{PORT}  (clientId={CLIENT_ID})")
    print(f"  Signals:    {len(targets)} from signals.csv")
    print(f"  Lmt Buffer: +{LMT_BUFFER_PCT * 100:.1f}% above market")

    # ── Init Supabase ─────────────────────────────────────────────────
    db = None
    if SUPABASE_URL and SUPABASE_KEY:
        db = SupabaseREST(SUPABASE_URL, SUPABASE_KEY)
        print(f"  Supabase:   CONNECTED")
    else:
        print(f"  Supabase:   SKIPPED (no credentials)")

    # ── Connect to IB Gateway ─────────────────────────────────────────
    section("Connecting to IB Gateway")

    ib = IB()
    ib.connect(HOST, PORT, clientId=CLIENT_ID, timeout=10)

    accounts = ib.managedAccounts()
    print(f"  Status:     CONNECTED")
    print(f"  Account:    {accounts[0] if accounts else 'N/A'}")

    # ── Fetch live prices & build order plan ──────────────────────────
    section("Fetching Live Prices")

    order_plan = []
    for target in targets:
        ticker = target["ticker"]
        contract = Stock(ticker, "SMART", "USD")
        qualified = ib.qualifyContracts(contract)

        if not qualified:
            print(f"  [{ticker}] FAILED: Could not qualify contract")
            order_plan.append({**target, "contract": None, "price": 0.0, "lmt": 0.0})
            continue

        price = fetch_current_price(ib, contract)
        lmt = round(price * (1 + LMT_BUFFER_PCT), 2)

        print(f"  [{ticker}] Current: ${price:,.2f}  ->  Limit: ${lmt:,.2f}  "
              f"(+{LMT_BUFFER_PCT * 100:.1f}%)  Trail: ${target['trailing_amt']:.2f}")

        order_plan.append({**target, "contract": contract, "price": price, "lmt": lmt})

    # ── Print order plan ──────────────────────────────────────────────
    section("Order Plan")
    print(f"  {'Ticker':>8}  {'Action':>6}  {'Qty':>5}  {'Price':>10}  "
          f"{'Limit':>10}  {'Trail $':>8}")
    print(f"  {'-' * 8}  {'-' * 6}  {'-' * 5}  {'-' * 10}  "
          f"{'-' * 10}  {'-' * 8}")
    for p in order_plan:
        print(f"  {p['ticker']:>8}  {'BUY':>6}  {p['qty']:>5}  "
              f"${p['price']:>9,.2f}  ${p['lmt']:>9,.2f}  ${p['trailing_amt']:>7,.2f}")

    # ── Submit bracket orders ─────────────────────────────────────────
    section("Submitting Bracket Orders")

    order_log = []

    for plan in order_plan:
        ticker = plan["ticker"]
        contract = plan["contract"]
        qty = plan["qty"]
        lmt = plan["lmt"]
        trail_amt = plan["trailing_amt"]

        if contract is None:
            order_log.append({"ticker": ticker, "status": "FAILED", "reason": "contract"})
            continue

        if plan["price"] <= 0:
            print(f"  [{ticker}] FAILED: Could not fetch price")
            order_log.append({"ticker": ticker, "status": "FAILED", "reason": "no price"})
            continue

        print(f"\n  [{ticker}] Contract: {contract.localSymbol} (conId={contract.conId})")

        bracket = create_bracket_order(
            action="BUY",
            quantity=qty,
            limit_price=lmt,
            trailing_amount=trail_amt,
        )

        parent_order, trail_order = bracket

        # Place parent (held -- transmit=False)
        ib.placeOrder(contract, parent_order)
        print(f"  [{ticker}] LEG 1/2  LMT BUY x{qty} @${lmt:,.2f}  "
              f"=> orderId={parent_order.orderId}  (transmit=False)")

        # Set parentId now that the parent has a real orderId
        trail_order.parentId = parent_order.orderId

        # Place child (fires everything -- transmit=True)
        ib.placeOrder(contract, trail_order)
        print(f"  [{ticker}] LEG 2/2  TRAIL STOP SELL x{qty} trail=${trail_amt:.2f}  "
              f"=> orderId={trail_order.orderId}  (transmit=True)")

        print(f"  [{ticker}] BRACKET SUBMITTED SUCCESSFULLY")

        order_log.append({
            "ticker": ticker,
            "status": "SUBMITTED",
            "parent_id": parent_order.orderId,
            "trail_id": trail_order.orderId,
            "lmt_price": lmt,
            "trail_amt": trail_amt,
        })

        # ── Insert into Supabase ──────────────────────────────────────
        if db:
            db_insert_trade(db, {
                "ticker": ticker,
                "entry_price": plan["price"],
                "stop_loss": plan["stop"],
                "take_profit": plan["tp"],
                "shares": qty,
                "trailing_amount": trail_amt,
                "status": "open",
                "current_price": plan["price"],
            })

    # ── Wait for transmission ─────────────────────────────────────────
    section("Confirming Transmission")
    print(f"  Waiting 2 seconds for order confirmation...")
    ib.sleep(2)

    open_orders = ib.openOrders()
    print(f"  Open orders on account: {len(open_orders)}")

    for entry in order_log:
        if entry["status"] == "SUBMITTED":
            print(f"  {entry['ticker']:>6}  =>  Parent(LMT)={entry['parent_id']}  "
                  f"Trail={entry['trail_id']}")

    # ── Disconnect ────────────────────────────────────────────────────
    ib.disconnect()

    # ── Final Summary ─────────────────────────────────────────────────
    banner("EXECUTION SUMMARY")
    submitted = sum(1 for e in order_log if e["status"] == "SUBMITTED")
    failed = sum(1 for e in order_log if e["status"] == "FAILED")

    print(f"  Brackets Submitted:  {submitted}")
    print(f"  Brackets Failed:     {failed}")
    print(f"  Total Legs Placed:   {submitted * 2}")
    print(f"  Supabase:            {'YES' if db else 'SKIPPED'}")
    print(f"  Status:              {'ALL ORDERS LIVE' if failed == 0 else 'PARTIAL EXECUTION'}")
    print()

    for entry in order_log:
        symbol = entry["ticker"]
        if entry["status"] == "SUBMITTED":
            print(f"    {symbol:>6}  LIVE  |  LMT BUY @${entry['lmt_price']:,.2f} "
                  f"+ TRAIL ${entry['trail_amt']:.2f}  "
                  f"|  IDs: {entry['parent_id']}/{entry['trail_id']}")
        else:
            print(f"    {symbol:>6}  FAIL  |  {entry.get('reason', 'unknown')}")

    print(f"\n{'=' * 78}")
    print(f"  Pipeline: scanner -> telegram -> signals.csv -> IBKR -> Supabase")
    print(f"  Monitor positions in TWS or IB Gateway.")
    print(f"{'=' * 78}\n")


if __name__ == "__main__":
    main()
